### ISSUE TITLE
Does dash-tradinview support volume bars?

### ISSUE THREAD

**Issue by pedropivotto** [tysonwu/dash-tradingview#1]

**Comment by tysonwu** [comment]
Hi there,
I have updated the supported chart types. Bars (aka. histograms, as defined from Tradingview's original lightweight chart) is now supported. You may find the following snippet modified from `usage.py` useful:
```
data = [{
        'seriesData': series_data,
        'seriesType': 'histogram',
}]
dash_tvlwc.Tvlwc(
    id='tv-chart',
    data=data
)
```

**Comment by pedropivotto** [comment]
Thanks TysonWu!  I'll take a look at the updated version.
