### ISSUE TITLE
time scale

### ISSUE THREAD

**Issue by apawitan1995** [tysonwu/dash-tradingview#3]
Hey there! was wondering if it is possible to change the time interval for this library. Seems like for now it only support daily data ? will it support hourly or minute data ?

**Comment by apawitan1995** [comment]
turns out need to put datetime as timestamp 🙏

**Comment by Anshufi** [comment]
@apawitan1995 bro Have you figured out how to do it , I have tried that you told but i see only one bar , and it seems like they are stacked on top of each other please help..

**Comment by tysonwu** [comment]
@Anshufi
You can pass in a timestamp instead of "business day" for the time field of that series. It is timestamp in seconds according to Tradingview's documentation here: https://tradingview.github.io/lightweight-charts/docs/3.8/api#time

**Comment by Anshufi** [comment]
@tysonwu Thanks for the reply brother, its working , and i want some more help 
1. how to create a sub plot in the chart like atr and sync them

**Comment by Anshufi** [comment]
> @Anshufi You can pass in a timestamp instead of "business day" for the time field of that series. It is timestamp in seconds according to Tradingview's documentation here: https://tradingview.github.io/lightweight-charts/docs/3.8/api#time
chart is plotting but only date shows on timescale , this is the timestamp '1609731900'
![Screenshot (247)](https://user-images.githubusercontent.com/95302059/226579351-9ce06927-cc5b-4029-92b8-43b358d257bb.png)

**Comment by brodiegould** [comment]
@tysonwu 
Just want to confirm that this will only plot daily data and not minute timeframe data right?
Looking to plot minute-to-minute data
