### ISSUE TITLE
How do we use hourly and minute timeframes

### ISSUE THREAD

**Issue by usherreuben** [tysonwu/dash-tradingview#6]
How do you plot 1 minute data.. it did not accept the time  form below:

'time': '2022-04-01 00:00:00'
'time': '2022-04-01 00:01:00'
'time': '2022-04-01 00:02:00'
'time': '2022-04-01 00:03:00'
'time': '2022-04-01 00:04:00'
'time': '2022-04-01 00:05:00'
'time': '2022-04-01 00:06:00'

is there are way i have to format the time or could a any one provide a working example.
Thanks.

**Comment by tysonwu** [comment]
Hi @usherreuben,
You can convert the datetimes into timestamp in seconds. See Issue #3 too.

**Comment by usherreuben** [comment]
Thank you it did work.👍
